### ISSUE TITLE
nan_to_num() got an unexpected keyword argument 'posinf'

### ISSUE THREAD

**Issue by RYucel** [giotto-ai/stock-market-crashes#1]
Error on "persistence diagrams" section. Tried the code for TRY=X and time series window as `start_date="2010-01-01",
    end_date="2019-01-01"`
Does not matter changing time window. Getting error as 
`nan_to_num() got an unexpected keyword argument 'posinf'`
How to solve it?

**Comment by lewtun** [comment]
Thanks for raising the error @stevevaius77. Can please be more specific about where the error originates from, e.g. by posting a snippet of the code that breaks?

**Comment by RYucel** [comment]
I run it on Colab and it worked. I guess Numpy version on local PC was problematic.
