### ISSUE TITLE
Request to specify version for giotto-tda for python notebook

### ISSUE THREAD

**Issue by StephanSalas** [giotto-ai/stock-market-crashes#7]
Reproducible issue:

pip install -r requirements.txt does not include the exact version needed for the python notebook for giotto-tda. It looks like the notebook currently uses giotto-tda==0.2.X, but if I do a pip install as-is, I see that the incorrect version is pulled for this notebook: https://github.com/giotto-ai/stock-market-crashes/blob/master/Stock%20Market%20Crash%20Detection.ipynb

Willing to contribute... let me know how I can further help.

**Comment by ulupo** [comment]
This should have been fixed in #9 which refactors the codebase form compatibility with `giotto-tda` 0.4.0.  Sorry this came so late.

**Comment by StephanSalas** [comment]
> This should have been fixed in #9 which refactors the codebase form compatibility with `giotto-tda` 0.4.0. Sorry this came so late.

NP! Thanks for the update! It's been a pleasure using this library.
